site_name: panduan aplikasi manajemen pegawai
theme:
  name: material
  palette:




    # Palette toggle for light mode
    - scheme: default
      primary:  lime  
      accent: lime
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary:  lime  
      accent: lime
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

#Mengstur font
  font:
    text: Open Sans 
    code: JetBrains Mono

# icon 
  logo: images/system.png
  favicon: images/system.png

  icon: 
    admoniton: 
      note: fontawesome/solid/note-sticky
      abstrack: fontawesome/solid/system
      info: fontawesome/solid/cicrcle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      qoute: fontawesome/solid/qoute-lift

  features:
    # - navigation.footer
    # - navigation.tabs

  markdown-ekstensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    
    #fitur
    - attr-list
    #keyboard
    - pymdownx.keys
    

#plugin search
plugins:
  - search

# Footer
copyright: Made with by kikuk | ᕦ(ò_óˇ)ᕤ

extra:
  generator: false

